'use client';

import { useState, useEffect, useCallback } from 'react';
import { rewardsApi, RewardCodeMode, RewardFormData } from '../../../lib/api';

interface MarketReward {
  id: string;
  slug: string;
  title: string;
  description: string;
  benefitText: string;
  discountLabel: string;
  minReputation: number;
  levelLabel: string;
  levelIcon: string;
  isActive: boolean;
  codeMode: RewardCodeMode;
  codePrefix?: string | null;
  autoExpiresDays: number;
  availableCodes: number;
  claimCount: number;
  autoGeneratedCodes: number;
}

const EMPTY_FORM: RewardFormData = {
  slug: '',
  title: '',
  description: '',
  benefitText: '',
  discountLabel: '%3 İndirim',
  minReputation: 1.5,
  levelLabel: 'Gözlemci',
  levelIcon: '🎁',
  codeMode: 'HYBRID',
  codePrefix: 'MKT',
  autoExpiresDays: 30,
  isActive: true,
};

export default function MarketRewardsPage() {
  const [rewards, setRewards] = useState<MarketReward[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedId, setSelectedId] = useState('');
  const [codesText, setCodesText] = useState('');
  const [adding, setAdding] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<RewardFormData>(EMPTY_FORM);
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const data = await rewardsApi.listMarket();
      setRewards(data ?? []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleAddCodes = async () => {
    if (!selectedId || !codesText.trim()) return;
    setAdding(true);
    try {
      const codes = codesText.split(/[\n,]+/).map((c) => c.trim()).filter(Boolean);
      await rewardsApi.addCodesMarket(selectedId, codes);
      setCodesText('');
      load();
      alert(`${codes.length} kod eklendi.`);
    } catch {
      alert('Kod eklenemedi.');
    } finally {
      setAdding(false);
    }
  };

  const openCreate = () => {
    setEditingId(null);
    setForm(EMPTY_FORM);
    setShowForm(true);
  };

  const openEdit = (r: MarketReward) => {
    setEditingId(r.id);
    setForm({
      slug: r.slug,
      title: r.title,
      description: r.description,
      benefitText: r.benefitText,
      discountLabel: r.discountLabel,
      minReputation: r.minReputation,
      levelLabel: r.levelLabel,
      levelIcon: r.levelIcon,
      codeMode: r.codeMode,
      codePrefix: r.codePrefix ?? 'MKT',
      autoExpiresDays: r.autoExpiresDays,
      isActive: r.isActive,
    });
    setShowForm(true);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      if (editingId) {
        const { slug, marketId, ...rest } = form;
        await rewardsApi.updateMarket(editingId, rest);
      } else {
        await rewardsApi.createMarket(form);
      }
      setShowForm(false);
      load();
    } catch {
      alert('Kaydedilemedi.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div>
      <div className="flex items-start justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-1">Topluluk Ödülleri</h1>
          <p className="text-sm text-gray-500">
            Marketinize özel itibar kuponları — manuel kod veya otomatik üretim.
          </p>
        </div>
        <button
          onClick={openCreate}
          className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-semibold"
        >
          + Yeni Kupon Kampanyası
        </button>
      </div>

      {loading ? (
        <div className="flex justify-center py-16">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500" />
        </div>
      ) : rewards.length === 0 ? (
        <div className="bg-white dark:bg-gray-900 rounded-2xl border p-8 text-center text-gray-500">
          Henüz ödül tanımlanmamış. İlk kampanyanızı oluşturun.
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2">
          {rewards.map((r) => (
            <div key={r.id} className="bg-white dark:bg-gray-900 rounded-2xl border p-5">
              <p className="text-lg font-bold dark:text-white">{r.levelIcon} {r.title}</p>
              <p className="text-xs text-gray-500 mt-1">{r.discountLabel} · min {r.minReputation} itibar · {r.codeMode}</p>
              <div className="grid grid-cols-3 gap-2 mt-4 text-center">
                <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-2">
                  <p className="text-lg font-bold text-green-600">{r.availableCodes}</p>
                  <p className="text-[10px] text-gray-500">Stok</p>
                </div>
                <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-2">
                  <p className="text-lg font-bold text-blue-600">{r.claimCount}</p>
                  <p className="text-[10px] text-gray-500">Talep</p>
                </div>
                <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-2">
                  <p className="text-lg font-bold text-purple-600">{r.autoGeneratedCodes}</p>
                  <p className="text-[10px] text-gray-500">Oto</p>
                </div>
              </div>
              <button onClick={() => openEdit(r)} className="mt-3 text-xs text-blue-600 font-semibold hover:underline">
                Düzenle
              </button>
            </div>
          ))}
        </div>
      )}

      <div className="mt-8 bg-white dark:bg-gray-900 rounded-2xl border p-5 max-w-lg">
        <h2 className="font-bold dark:text-white mb-3">Manuel Kod Ekle</h2>
        <select
          className="w-full border rounded-xl px-3 py-2 text-sm mb-3 dark:bg-gray-800 dark:text-white"
          value={selectedId}
          onChange={(e) => setSelectedId(e.target.value)}
        >
          <option value="">Ödül seçin</option>
          {rewards.map((r) => <option key={r.id} value={r.id}>{r.title}</option>)}
        </select>
        <textarea
          className="w-full border rounded-xl px-3 py-2 text-sm h-24 dark:bg-gray-800 dark:text-white"
          placeholder="Her satıra bir kod"
          value={codesText}
          onChange={(e) => setCodesText(e.target.value)}
        />
        <button
          onClick={handleAddCodes}
          disabled={adding || !selectedId}
          className="mt-3 w-full py-2.5 bg-blue-600 text-white rounded-xl font-semibold text-sm disabled:opacity-50"
        >
          {adding ? 'Ekleniyor...' : 'Kodları Ekle'}
        </button>
      </div>

      {showForm && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-900 rounded-2xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <h2 className="text-lg font-bold mb-4 dark:text-white">
              {editingId ? 'Kampanya Düzenle' : 'Yeni Kampanya'}
            </h2>
            <div className="space-y-3">
              {!editingId && (
                <input className="w-full border rounded-xl px-3 py-2 text-sm dark:bg-gray-800 dark:text-white"
                  placeholder="Slug" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} />
              )}
              <input className="w-full border rounded-xl px-3 py-2 text-sm dark:bg-gray-800 dark:text-white"
                placeholder="Başlık" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
              <textarea className="w-full border rounded-xl px-3 py-2 text-sm dark:bg-gray-800 dark:text-white"
                placeholder="Açıklama" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} />
              <input className="w-full border rounded-xl px-3 py-2 text-sm dark:bg-gray-800 dark:text-white"
                placeholder="Fayda" value={form.benefitText} onChange={(e) => setForm({ ...form, benefitText: e.target.value })} />
              <select className="w-full border rounded-xl px-3 py-2 text-sm dark:bg-gray-800 dark:text-white"
                value={form.codeMode} onChange={(e) => setForm({ ...form, codeMode: e.target.value as RewardCodeMode })}>
                <option value="HYBRID">Hibrit</option>
                <option value="AUTO">Otomatik</option>
                <option value="MANUAL">Manuel</option>
              </select>
              <input className="w-full border rounded-xl px-3 py-2 text-sm dark:bg-gray-800 dark:text-white"
                placeholder="Kod öneki" value={form.codePrefix} onChange={(e) => setForm({ ...form, codePrefix: e.target.value })} />
            </div>
            <div className="flex gap-2 mt-6">
              <button onClick={() => setShowForm(false)} className="flex-1 py-2 border rounded-xl text-sm">İptal</button>
              <button onClick={handleSave} disabled={saving}
                className="flex-1 py-2 bg-blue-600 text-white rounded-xl text-sm font-semibold disabled:opacity-50">
                {saving ? 'Kaydediliyor...' : 'Kaydet'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
