'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import { rewardsApi, marketsApi, RewardCodeMode, RewardFormData } from '../../../lib/api';
import { useColors } from '../../../context/ThemeContext';
import { SectionCard } from '../../../components/statistics/StatsUI';
import {
  AdminToast, PageHero, TabBar, EmptyState, LoadingCenter, ProgressBar,
} from '../../../components/admin/AdminUIKit';

interface AdminReward {
  id: string;
  slug: string;
  title: string;
  description: string;
  benefitText: string;
  discountLabel: string;
  minReputation: number;
  levelLabel: string;
  levelIcon: string;
  instructions?: string | null;
  isActive: boolean;
  codeMode: RewardCodeMode;
  codePrefix?: string | null;
  autoExpiresDays: number;
  sortOrder: number;
  market?: { id: string; name: string } | null;
  totalCodes: number;
  availableCodes: number;
  usedCodes: number;
  claimCount: number;
  autoGeneratedCodes: number;
}

interface ClaimRow {
  id: string;
  claimedAt: string;
  code: string;
  codeSource: 'MANUAL' | 'AUTO';
  user: { email: string; name?: string; reputationScore: number };
}

const CODE_MODE_META: Record<RewardCodeMode, { label: string; color: string; icon: string; desc: string }> = {
  MANUAL: { label: 'Manuel Havuz', color: '#94a3b8', icon: '📋', desc: 'Yalnızca eklediğiniz kodlardan dağıtım' },
  AUTO:   { label: 'Otomatik', color: '#a78bfa', icon: '⚡', desc: 'Talep anında otomatik kod üretimi' },
  HYBRID: { label: 'Hibrit', color: '#60a5fa', icon: '🔀', desc: 'Önce havuz, yoksa otomatik üret' },
};

const EMPTY_FORM: RewardFormData = {
  slug: '', title: '', description: '', benefitText: '',
  discountLabel: '%5 İndirim', minReputation: 2, levelLabel: 'Gözlemci', levelIcon: '🎁',
  codeMode: 'HYBRID', codePrefix: 'AKS', autoExpiresDays: 30, sortOrder: 0, isActive: true,
};

type TabKey = 'campaigns' | 'codes' | 'claims';

function formatDate(iso: string) {
  return new Date(iso).toLocaleString('tr-TR', {
    day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

function FormField({ label, children, C }: { label: string; children: React.ReactNode; C: ReturnType<typeof useColors> }) {
  return (
    <div>
      <label className="text-[10px] font-bold uppercase tracking-widest block mb-1.5" style={{ color: C.muted }}>{label}</label>
      {children}
    </div>
  );
}

function inputStyle(C: ReturnType<typeof useColors>): React.CSSProperties {
  return { background: C.cardAlt, border: `1px solid ${C.border}`, color: C.text };
}

function RewardFormModal({
  open, editingId, form, setForm, markets, saving, onClose, onSave, C,
}: {
  open: boolean; editingId: string | null; form: RewardFormData;
  setForm: React.Dispatch<React.SetStateAction<RewardFormData>>;
  markets: Array<{ id: string; name: string }>; saving: boolean;
  onClose: () => void; onSave: () => void; C: ReturnType<typeof useColors>;
}) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  if (!open) return null;
  const inp = 'w-full rounded-xl px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-400/40';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(0,0,0,0.65)', backdropFilter: 'blur(8px)' }} onClick={onClose}>
      <div className="w-full max-w-lg max-h-[90vh] rounded-2xl overflow-hidden flex flex-col"
        style={{ background: C.card, border: `1px solid ${C.border}` }} onClick={(e) => e.stopPropagation()}>
        <div className="px-6 py-4 shrink-0" style={{ borderBottom: `1px solid ${C.border}`, background: C.cardAlt }}>
          <p className="text-[10px] font-bold uppercase tracking-widest" style={{ color: C.purple }}>
            {editingId ? 'Kampanya Düzenle' : 'Yeni Kampanya'}
          </p>
          <h2 className="text-lg font-bold mt-0.5">{editingId ? form.title || 'Ödül' : 'Topluluk Ödülü Oluştur'}</h2>
        </div>
        <div className="overflow-y-auto p-6 space-y-4 flex-1">
          {!editingId && (
            <FormField label="Slug (benzersiz)" C={C}>
              <input className={inp} style={inputStyle(C)} placeholder="bim-ozel-indirim"
                value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} />
            </FormField>
          )}
          <FormField label="Başlık" C={C}>
            <input className={inp} style={inputStyle(C)} value={form.title}
              onChange={(e) => setForm({ ...form, title: e.target.value })} />
          </FormField>
          <FormField label="Açıklama" C={C}>
            <textarea className={`${inp} resize-none`} style={inputStyle(C)} rows={2}
              value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} />
          </FormField>
          <FormField label="Fayda Metni" C={C}>
            <input className={inp} style={inputStyle(C)} value={form.benefitText}
              onChange={(e) => setForm({ ...form, benefitText: e.target.value })} />
          </FormField>
          <div className="grid grid-cols-2 gap-3">
            <FormField label="İndirim Etiketi" C={C}>
              <input className={inp} style={inputStyle(C)} value={form.discountLabel}
                onChange={(e) => setForm({ ...form, discountLabel: e.target.value })} />
            </FormField>
            <FormField label="Min. İtibar" C={C}>
              <input type="number" step="0.1" className={inp} style={inputStyle(C)}
                value={form.minReputation} onChange={(e) => setForm({ ...form, minReputation: parseFloat(e.target.value) || 0 })} />
            </FormField>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <FormField label="Seviye" C={C}>
              <input className={inp} style={inputStyle(C)} value={form.levelLabel}
                onChange={(e) => setForm({ ...form, levelLabel: e.target.value })} />
            </FormField>
            <FormField label="İkon" C={C}>
              <input className={inp} style={inputStyle(C)} value={form.levelIcon}
                onChange={(e) => setForm({ ...form, levelIcon: e.target.value })} />
            </FormField>
          </div>
          <FormField label="Partner Market" C={C}>
            <select className={inp} style={inputStyle(C)} value={form.marketId ?? ''}
              onChange={(e) => setForm({ ...form, marketId: e.target.value || undefined })}>
              <option value="">Market seçin…</option>
              {markets.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}
            </select>
          </FormField>
          <FormField label="Kod Modu" C={C}>
            <select className={inp} style={inputStyle(C)} value={form.codeMode}
              onChange={(e) => setForm({ ...form, codeMode: e.target.value as RewardCodeMode })}>
              <option value="HYBRID">Hibrit</option>
              <option value="AUTO">Otomatik</option>
              <option value="MANUAL">Manuel</option>
            </select>
          </FormField>
          <div className="grid grid-cols-2 gap-3">
            <FormField label="Kod Öneki" C={C}>
              <input className={inp} style={inputStyle(C)} value={form.codePrefix}
                onChange={(e) => setForm({ ...form, codePrefix: e.target.value })} />
            </FormField>
            <FormField label="Geçerlilik (gün)" C={C}>
              <input type="number" className={inp} style={inputStyle(C)}
                value={form.autoExpiresDays} onChange={(e) => setForm({ ...form, autoExpiresDays: parseInt(e.target.value, 10) || 30 })} />
            </FormField>
          </div>
          <label className="flex items-center gap-2 cursor-pointer">
            <input type="checkbox" checked={form.isActive}
              onChange={(e) => setForm({ ...form, isActive: e.target.checked })} className="w-4 h-4 accent-blue-600" />
            <span className="text-sm font-semibold">Kampanya aktif</span>
          </label>
        </div>
        <div className="flex gap-3 px-6 py-4 shrink-0" style={{ borderTop: `1px solid ${C.border}`, background: C.cardAlt }}>
          <button type="button" onClick={onClose} className="flex-1 py-2.5 rounded-xl text-sm font-bold"
            style={{ background: C.card, border: `1px solid ${C.border}`, color: C.secondary }}>İptal</button>
          <button type="button" onClick={onSave} disabled={saving}
            className="flex-1 py-2.5 rounded-xl text-sm font-bold text-white disabled:opacity-40"
            style={{ background: C.blue }}>{saving ? 'Kaydediliyor…' : editingId ? 'Güncelle' : 'Oluştur'}</button>
        </div>
      </div>
    </div>
  );
}

export default function RewardsAdminPage() {
  const C = useColors();
  const [rewards, setRewards] = useState<AdminReward[]>([]);
  const [markets, setMarkets] = useState<Array<{ id: string; name: string }>>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<TabKey>('campaigns');
  const [search, setSearch] = useState('');
  const [filterActive, setFilterActive] = useState<'all' | 'active' | 'inactive'>('all');
  const [selectedId, setSelectedId] = useState('');
  const [codesText, setCodesText] = useState('');
  const [adding, setAdding] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<RewardFormData>(EMPTY_FORM);
  const [saving, setSaving] = useState(false);
  const [claims, setClaims] = useState<ClaimRow[]>([]);
  const [claimsLoading, setClaimsLoading] = useState(false);
  const [toast, setToast] = useState<{ msg: string; err?: boolean } | null>(null);

  const showToast = (msg: string, err = false) => {
    setToast({ msg, err });
    setTimeout(() => setToast(null), 3000);
  };

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [data, mkts] = await Promise.all([rewardsApi.listAdmin(), marketsApi.getAll()]);
      setRewards(data ?? []);
      setMarkets(mkts);
    } catch { /* ignore */ }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { load(); }, [load]);

  const filteredRewards = useMemo(() => {
    let list = rewards;
    if (filterActive === 'active') list = list.filter((r) => r.isActive);
    if (filterActive === 'inactive') list = list.filter((r) => !r.isActive);
    if (search.trim()) {
      const q = search.toLowerCase();
      list = list.filter((r) =>
        r.title.toLowerCase().includes(q) ||
        r.market?.name.toLowerCase().includes(q) ||
        r.slug.toLowerCase().includes(q),
      );
    }
    return list;
  }, [rewards, search, filterActive]);

  const loadClaims = async (rewardId: string) => {
    setClaimsLoading(true);
    try {
      setClaims((await rewardsApi.listClaims(rewardId)) ?? []);
    } catch { setClaims([]); }
    finally { setClaimsLoading(false); }
  };

  const handleSelectReward = (id: string) => {
    setSelectedId(id);
    if (id) loadClaims(id);
    else setClaims([]);
  };

  const handleAddCodes = async () => {
    if (!selectedId || !codesText.trim()) return;
    setAdding(true);
    try {
      const codes = codesText.split(/[\n,]+/).map((c) => c.trim()).filter(Boolean);
      await rewardsApi.addCodes(selectedId, codes);
      setCodesText('');
      load();
      showToast(`${codes.length} kod eklendi`);
    } catch { showToast('Kod eklenemedi', true); }
    finally { setAdding(false); }
  };

  const openCreate = () => { setEditingId(null); setForm(EMPTY_FORM); setShowForm(true); };
  const openEdit = (r: AdminReward) => {
    setEditingId(r.id);
    setForm({
      slug: r.slug, title: r.title, description: r.description, benefitText: r.benefitText,
      discountLabel: r.discountLabel, minReputation: r.minReputation, levelLabel: r.levelLabel,
      levelIcon: r.levelIcon, instructions: r.instructions ?? undefined, marketId: r.market?.id,
      codeMode: r.codeMode, codePrefix: r.codePrefix ?? 'AKS', autoExpiresDays: r.autoExpiresDays,
      sortOrder: r.sortOrder, isActive: r.isActive,
    });
    setShowForm(true);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      if (editingId) {
        const { slug, ...rest } = form;
        await rewardsApi.updateAdmin(editingId, rest);
        showToast('Kampanya güncellendi');
      } else {
        await rewardsApi.createAdmin(form);
        showToast('Kampanya oluşturuldu');
      }
      setShowForm(false);
      load();
    } catch { showToast('Kaydedilemedi', true); }
    finally { setSaving(false); }
  };

  const totalClaims = rewards.reduce((s, r) => s + r.claimCount, 0);
  const totalAvailable = rewards.reduce((s, r) => s + r.availableCodes, 0);
  const activeCount = rewards.filter((r) => r.isActive).length;
  const selectedReward = rewards.find((r) => r.id === selectedId);

  return (
    <div className="space-y-6 max-w-[1400px]" style={{ color: C.text }}>
      {toast && <AdminToast message={toast.msg} error={toast.err} />}

      <PageHero
        badge="Topluluk Ödül Merkezi"
        title="İtibar Kuponları"
        subtitle="Partner market indirimleri — manuel havuz, otomatik üretim veya hibrit mod ile itibar karşılığı kupon dağıtımı."
        gradient="linear-gradient(135deg, #4c1d95 0%, #6d28d9 45%, #db2777 100%)"
        actions={(
          <button onClick={openCreate}
            className="px-5 py-2.5 rounded-xl text-sm font-black text-white"
            style={{ background: 'rgba(255,255,255,0.2)', border: '1px solid rgba(255,255,255,0.35)' }}>
            + Yeni Kampanya
          </button>
        )}
        metrics={[
          { label: 'Aktif Kampanya', value: activeCount, icon: '✅' },
          { label: 'Toplam Talep', value: totalClaims, icon: '📥' },
          { label: 'Müsait Kod', value: totalAvailable, icon: '📋' },
          { label: 'Tüm Kampanya', value: rewards.length, icon: '🎁' },
        ]}
      />

      {/* Kod modu rehberi */}
      <div className="grid sm:grid-cols-3 gap-3">
        {(Object.entries(CODE_MODE_META) as [RewardCodeMode, typeof CODE_MODE_META.MANUAL][]).map(([key, m]) => (
          <div key={key} className="rounded-xl p-4" style={{ background: C.card, border: `1px solid ${C.border}` }}>
            <p className="text-sm font-black" style={{ color: m.color }}>{m.icon} {m.label}</p>
            <p className="text-[11px] mt-1" style={{ color: C.muted }}>{m.desc}</p>
          </div>
        ))}
      </div>

      <TabBar<TabKey>
        active={tab}
        onChange={setTab}
        tabs={[
          { key: 'campaigns', label: 'Kampanyalar', icon: '🎁', count: rewards.length },
          { key: 'codes', label: 'Kod Ekle', icon: '📋' },
          { key: 'claims', label: 'Talep Geçmişi', icon: '📊', count: totalClaims },
        ]}
      />

      {tab === 'campaigns' && (
        <>
          <div className="flex flex-wrap gap-3">
            <input
              type="search"
              placeholder="Kampanya veya market ara…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="flex-1 min-w-[200px] rounded-xl px-4 py-2.5 text-sm outline-none"
              style={{ background: C.card, border: `1px solid ${C.border}`, color: C.text }}
            />
            <select value={filterActive} onChange={(e) => setFilterActive(e.target.value as typeof filterActive)}
              className="rounded-xl px-4 py-2.5 text-sm outline-none"
              style={{ background: C.card, border: `1px solid ${C.border}`, color: C.text }}>
              <option value="all">Tümü</option>
              <option value="active">Aktif</option>
              <option value="inactive">Pasif</option>
            </select>
          </div>

          {loading ? (
            <LoadingCenter />
          ) : filteredRewards.length === 0 ? (
            <EmptyState icon="🎁" title="Kampanya bulunamadı" subtitle="Yeni bir itibar kuponu kampanyası oluşturun."
              action={<button onClick={openCreate} className="px-6 py-2.5 rounded-xl text-sm font-bold text-white" style={{ background: C.blue }}>+ Oluştur</button>} />
          ) : (
            <div className="grid gap-4 md:grid-cols-2">
              {filteredRewards.map((r) => {
                const mode = CODE_MODE_META[r.codeMode];
                const poolUsed = r.totalCodes > 0 ? Math.round((r.usedCodes / r.totalCodes) * 100) : 0;
                return (
                  <article key={r.id} className="rounded-2xl overflow-hidden transition-all hover:shadow-lg"
                    style={{ background: C.card, border: `1px solid ${C.border}` }}>
                    <div className="p-5">
                      <div className="flex items-start gap-3">
                        <div className="w-14 h-14 rounded-2xl flex items-center justify-center text-2xl shrink-0"
                          style={{ background: `linear-gradient(135deg, ${C.purple}22, ${C.blue}18)` }}>
                          {r.levelIcon}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-start justify-between gap-2">
                            <p className="font-black text-base truncate">{r.title}</p>
                            <span className="text-[9px] font-black px-2 py-1 rounded-lg shrink-0"
                              style={r.isActive ? { background: `${C.green}18`, color: C.green } : { background: C.cardAlt, color: C.muted }}>
                              {r.isActive ? 'AKTİF' : 'PASİF'}
                            </span>
                          </div>
                          <p className="text-xs mt-0.5" style={{ color: C.muted }}>
                            {r.market?.name ?? 'Genel'} · min {r.minReputation} itibar · {r.levelLabel}
                          </p>
                          <div className="flex flex-wrap gap-1.5 mt-2">
                            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full" style={{ background: `${C.blue}18`, color: C.blue }}>
                              {r.discountLabel}
                            </span>
                            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full" style={{ background: `${mode.color}18`, color: mode.color }}>
                              {mode.icon} {mode.label}
                            </span>
                          </div>
                        </div>
                      </div>

                      <div className="mt-4">
                        <div className="flex justify-between text-[10px] mb-1">
                          <span style={{ color: C.muted }}>Kod havuzu kullanımı</span>
                          <span className="font-bold">{r.usedCodes}/{r.totalCodes || '—'}</span>
                        </div>
                        <ProgressBar value={r.usedCodes} max={r.totalCodes || 1} color={poolUsed > 80 ? C.amber : C.green} />
                      </div>

                      <div className="grid grid-cols-4 gap-2 mt-4">
                        {[
                          { label: 'Müsait', value: r.availableCodes, color: C.green },
                          { label: 'Kullanılan', value: r.usedCodes, color: C.secondary },
                          { label: 'Talep', value: r.claimCount, color: C.blue },
                          { label: 'Oto', value: r.autoGeneratedCodes, color: C.purple },
                        ].map((s) => (
                          <div key={s.label} className="rounded-xl p-2 text-center" style={{ background: C.cardAlt }}>
                            <p className="text-base font-black tabular-nums" style={{ color: s.color }}>{s.value}</p>
                            <p className="text-[8px] font-bold uppercase mt-0.5" style={{ color: C.muted }}>{s.label}</p>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="px-5 py-3 flex gap-2" style={{ borderTop: `1px solid ${C.border}`, background: C.cardAlt }}>
                      <button onClick={() => openEdit(r)} className="flex-1 py-2 rounded-xl text-xs font-bold"
                        style={{ background: C.card, border: `1px solid ${C.border}` }}>Düzenle</button>
                      <button onClick={() => { setTab('codes'); setSelectedId(r.id); }}
                        className="flex-1 py-2 rounded-xl text-xs font-bold"
                        style={{ background: `${C.blue}12`, color: C.blue }}>Kod Ekle</button>
                      <button onClick={() => { setTab('claims'); handleSelectReward(r.id); }}
                        className="flex-1 py-2 rounded-xl text-xs font-bold"
                        style={{ background: `${C.purple}12`, color: C.purple }}>Talepler</button>
                    </div>
                  </article>
                );
              })}
            </div>
          )}
        </>
      )}

      {tab === 'codes' && (
        <SectionCard title="Manuel Kupon Kodu Ekle" desc="Her satıra bir kod. Hibrit modda havuz önceliklidir.">
          <div className="space-y-4 max-w-2xl">
            {selectedReward && (
              <div className="rounded-xl p-4 flex items-center gap-3" style={{ background: `${C.purple}10`, border: `1px solid ${C.purple}25` }}>
                <span className="text-2xl">{selectedReward.levelIcon}</span>
                <div>
                  <p className="text-sm font-bold">{selectedReward.title}</p>
                  <p className="text-xs" style={{ color: C.muted }}>{selectedReward.availableCodes} müsait kod</p>
                </div>
              </div>
            )}
            <FormField label="Hedef Kampanya" C={C}>
              <select className="w-full rounded-xl px-3 py-2.5 text-sm outline-none" style={inputStyle(C)}
                value={selectedId} onChange={(e) => handleSelectReward(e.target.value)}>
                <option value="">Kampanya seçin…</option>
                {rewards.map((r) => (
                  <option key={r.id} value={r.id}>{r.levelIcon} {r.title} ({r.availableCodes} müsait)</option>
                ))}
              </select>
            </FormField>
            <FormField label="Kupon Kodları" C={C}>
              <textarea className="w-full rounded-xl px-3 py-2.5 text-sm font-mono resize-none outline-none" style={inputStyle(C)} rows={8}
                placeholder={'BIM-001\nBIM-002\nBIM-003'} value={codesText} onChange={(e) => setCodesText(e.target.value)} />
              <p className="text-[10px] mt-1" style={{ color: C.muted }}>
                {codesText.split(/[\n,]+/).filter((c) => c.trim()).length} kod yazıldı
              </p>
            </FormField>
            <button onClick={handleAddCodes} disabled={adding || !selectedId}
              className="w-full py-3.5 rounded-xl text-sm font-black text-white disabled:opacity-40"
              style={{ background: 'linear-gradient(135deg, #2563eb, #7c3aed)' }}>
              {adding ? 'Ekleniyor…' : 'Kodları Havuza Ekle'}
            </button>
          </div>
        </SectionCard>
      )}

      {tab === 'claims' && (
        <SectionCard title="Talep Geçmişi" desc="Kullanıcıların aldığı kuponlar — otomatik ve manuel ayrımı.">
          <div className="space-y-4">
            <FormField label="Kampanya" C={C}>
              <select className="w-full max-w-md rounded-xl px-3 py-2.5 text-sm outline-none" style={inputStyle(C)}
                value={selectedId} onChange={(e) => handleSelectReward(e.target.value)}>
                <option value="">Kampanya seçin…</option>
                {rewards.map((r) => <option key={r.id} value={r.id}>{r.title} ({r.claimCount} talep)</option>)}
              </select>
            </FormField>

            {!selectedId ? (
              <p className="text-sm py-8 text-center" style={{ color: C.muted }}>Talep geçmişi için kampanya seçin</p>
            ) : claimsLoading ? (
              <LoadingCenter />
            ) : claims.length === 0 ? (
              <EmptyState icon="📊" title="Henüz talep yok" subtitle="Bu kampanyada kullanıcı talebi bulunmuyor." />
            ) : (
              <div className="rounded-xl overflow-hidden" style={{ border: `1px solid ${C.border}` }}>
                <table className="w-full text-sm">
                  <thead>
                    <tr style={{ background: C.cardAlt }}>
                      {['Kod', 'Kaynak', 'Kullanıcı', 'İtibar', 'Tarih'].map((h) => (
                        <th key={h} className="text-left px-4 py-3 text-[10px] font-bold uppercase tracking-wider" style={{ color: C.muted }}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {claims.map((c) => (
                      <tr key={c.id} style={{ borderTop: `1px solid ${C.border}` }} className="hover:brightness-[1.02]">
                        <td className="px-4 py-3 font-mono font-bold text-xs">{c.code}</td>
                        <td className="px-4 py-3">
                          <span className="text-[10px] font-bold px-2 py-0.5 rounded-full"
                            style={c.codeSource === 'AUTO' ? { background: `${C.purple}18`, color: C.purple } : { background: C.cardAlt, color: C.secondary }}>
                            {c.codeSource === 'AUTO' ? '⚡ Oto' : '📋 Manuel'}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <p className="text-xs font-medium">{c.user.name ?? c.user.email}</p>
                          <p className="text-[10px]" style={{ color: C.muted }}>{c.user.email}</p>
                        </td>
                        <td className="px-4 py-3 text-xs tabular-nums">{c.user.reputationScore.toFixed(1)}</td>
                        <td className="px-4 py-3 text-xs" style={{ color: C.muted }}>{formatDate(c.claimedAt)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </SectionCard>
      )}

      <RewardFormModal open={showForm} editingId={editingId} form={form} setForm={setForm}
        markets={markets} saving={saving} onClose={() => setShowForm(false)} onSave={handleSave} C={C} />
    </div>
  );
}
